#!/bin/bash

\rm electron_firm* ;

particle compile electron --target 0.6.1 \
	runner.cpp example_01.cpp example_02.cpp \
	../unit-test.h ../unit-test.cpp \
	../unit-test-helpers.h \
	../FakeStream.h ../FakeStream.cpp \
	../FakeStreamBuffer.h ../FakeStreamBuffer.cpp \
	../flashee-eeprom-impl.h \
	../flashee-eeprom.h ../flashee-eeprom.cpp \
;

stty -f /dev/tty.usbmodem142* 14400 ;

particle flash --usb electron_firm* ;